services:
  - type: web
    name: ultradoc-rag-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_UPGRADE_STRATEGY
        value: only-if-needed
